// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Kyutech-C3"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/resize": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resize"
                ],
                "summary": "画像のリサイズ",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "width",
                        "name": "w",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "height",
                        "name": "h",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "quality",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "string",
                        "description": "format",
                        "name": "f",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.ResizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resize"
                ],
                "summary": "画像のリサイズ",
                "parameters": [
                    {
                        "type": "file",
                        "description": "this is a file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "width",
                        "name": "w",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "height",
                        "name": "h",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "int64",
                        "description": "quality",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "string",
                        "description": "format",
                        "name": "f",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.ResizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.ResizeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Image Resize API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
